[libdefaults]
    default_realm = ARDEN.TEST
    dns_lookup_kdc = false
    dns_lookup_realm = false
    rdns = false
    forwardable = true

[realms]
    ARDEN.TEST = {
        kdc = ipa.arden.test
        admin_server = ipa.arden.test
    }

[domain_realm]
    .arden.test = ARDEN.TEST
    arden.test = ARDEN.TEST
